MusicoWebMVC/Models/ErrorViewModel.cs
using System;

namespace MusicoWebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MusicoWebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MusicoWebMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MusicoWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MusicoWebMVC/Controllers/MusicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Domain.Interfaces.Repositories;
using Domain.Interfaces.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;

namespace MusicoWebMVC.Controllers
{
    public class MusicoController : Controller
    {
        private readonly IMusicoRepository _musicoRepository;
        private readonly IBlobService _blobService;
        private readonly IConfiguration _configuration;
        private readonly IQueueService _queueService;

        public MusicoController(IMusicoRepository musicoRepository,
                                IBlobService blobService,
                                IConfiguration configuration,
                                IQueueService queueService)
        {
            _musicoRepository = musicoRepository;
            _blobService = blobService;
            _configuration = configuration;
            _queueService = queueService;
        }

        // GET: Musico
        public async Task<IActionResult> Index()
        {
            return View(await _musicoRepository.GetAllAsync());
        }

        // GET: Musico/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var httpClient = new HttpClient();
            //var json = JsonConvert.SerializeObject(new { musicoId = id });
            //var requestData = new StringContent(json, Encoding.UTF8, "application/json");
            //var baseAddressFunction = _configuration.GetValue<string>("FunctionBaseAddress");
            //_ = await httpClient.PostAsync(baseAddressFunction, requestData);

            var musicoModel = await _musicoRepository.GetByIdAsync(id.Value);

            var jsonMusico = JsonConvert.SerializeObject(musicoModel);
            var bytesJsonMusico = UTF8Encoding.UTF8.GetBytes(jsonMusico);
            string jsonMusicoBase64 = Convert.ToBase64String(bytesJsonMusico);

            await _queueService.SendAsync(jsonMusicoBase64);


            if (musicoModel == null)
            {
                return NotFound();
            }

            return View(musicoModel);
        }

        // GET: Musico/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Musico/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection form, MusicoModel musicoModel)
        {
            if (ModelState.IsValid)
            {
                var file = form.Files.SingleOrDefault();
                var streamFile = file.OpenReadStream();
                var uriImage = await _blobService.UploadAsync(streamFile);
                musicoModel.ImageUri = uriImage;

                await _musicoRepository.CreateAsync(musicoModel);
                return RedirectToAction(nameof(Index));
            }
            return View(musicoModel);
        }

        // GET: Musico/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicoModel = await _musicoRepository.GetByIdAsync(id.Value);

            if (musicoModel == null)
            {
                return NotFound();
            }
            return View(musicoModel);
        }

        // POST: Musico/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection form, 
                                              int id, 
                                              MusicoModel musicoModel)
        {
            if (id != musicoModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var file = form.Files.SingleOrDefault();
                    var streamFile = file?.OpenReadStream();

                    if (streamFile != null)
                    {
                        var uriImage = await _blobService.UploadAsync(streamFile);

                        if (musicoModel.ImageUri != null)
                        {
                            await _blobService.DeleteAsync(musicoModel.ImageUri);
                        }

                        musicoModel.ImageUri = uriImage;
                    }

                    await _musicoRepository.EditAsync(musicoModel);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MusicoModelExists(musicoModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(musicoModel);
        }

        // GET: Musico/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicoModel = await _musicoRepository.GetByIdAsync(id.Value);

            if (musicoModel == null)
            {
                return NotFound();
            }

            return View(musicoModel);
        }

        // POST: Musico/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var musico = _musicoRepository.GetByIdAsync(id).Result;

            if (musico.ImageUri != null)
            {
                await _blobService.DeleteAsync(musico.ImageUri);
            }

            await _musicoRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool MusicoModelExists(int id)
        {
            var musico = _musicoRepository.GetByIdAsync(id).Result;

            return (musico != null);
        }
    }
}

MusicoWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MusicoWebMVC/Views/Musico/Create.cshtml
@model Domain.Models.MusicoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Perfil do musico</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ImageUri" class="control-label"></label>
                <input type="file" asp-for="ImageUri" class="form-control btn " required accept=".jpg, .png" />
                <span asp-validation-for="ImageUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimoNome" class="control-label"></label>
                <input asp-for="UltimoNome" class="form-control" />
                <span asp-validation-for="UltimoNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantosInstrumentos" class="control-label"></label>
                <input asp-for="QuantosInstrumentos" class="form-control" />
                <span asp-validation-for="QuantosInstrumentos" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PossuiBanda" /> @Html.DisplayNameFor(model => model.PossuiBanda)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicoWebMVC/Views/Musico/Delete.cshtml
@model Domain.Models.MusicoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar perfil do musico</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUri)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUri)
        </dd>
        <dd class="col-sm-12">
            <img src="@Model.ImageUri" width="200" /> <br /><br />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UltimoNome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UltimoNome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuantosInstrumentos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuantosInstrumentos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PossuiBanda)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PossuiBanda)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUri)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUri)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visualizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visualizacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

MusicoWebMVC/Views/Musico/Details.cshtml
@model Domain.Models.MusicoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Detailhes do perfil</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUri)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUri)
        </dd>

        <dd class="col-sm-12">
            <img src="@Model.ImageUri" width="200" /> <br /><br />
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UltimoNome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UltimoNome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuantosInstrumentos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuantosInstrumentos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PossuiBanda)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PossuiBanda)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visualizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visualizacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

MusicoWebMVC/Views/Musico/Edit.cshtml
@model Domain.Models.MusicoModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar perfil do musico</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <img src="@Model.ImageUri " width="200" /><br /><br />
                <input type="hidden" asp-for="ImageUri" />
                <input type="file" name=" foto de perfil" class="form-control" accept=".jpg, .png" />
                <span asp-validation-for="ImageUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimoNome" class="control-label"></label>
                <input asp-for="UltimoNome" class="form-control" />
                <span asp-validation-for="UltimoNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantosInstrumentos" class="control-label"></label>
                <input asp-for="QuantosInstrumentos" class="form-control" />
                <span asp-validation-for="QuantosInstrumentos" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PossuiBanda" /> @Html.DisplayNameFor(model => model.PossuiBanda)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicoWebMVC/Views/Musico/Index.cshtml
@model IEnumerable<Domain.Models.MusicoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImageUri)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimoNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantosInstrumentos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PossuiBanda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Visualizacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ImageUri)" width="25" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UltimoNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantosInstrumentos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PossuiBanda)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Visualizacao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>

MusicoWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicoWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicoWebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Musico" asp-action="Index">Lista de musicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MusicoWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>